version: "2"
run:
  go: "1.24"

linters:
  default: none
  enable:
    - govet
    - errcheck
    - ineffassign
    - misspell
    - goconst
    - staticcheck
    - lll
    - unused
    - whitespace
  
  settings:
    goconst:
      min-occurrences: 2
      min-len: 2
    lll:
      line-length: 140
    misspell:
      locale: US

formatters:
  enable:
    - gofmt